### ISSUE TITLE
Write10X using Seurat and Cell Ranger v3 

### ISSUE THREAD

**Issue by jdime** [daskelly/earlycross#1]
Hello,

I'm using `signac` v0.1

Two related things:
1) Any plans to upgrade the Write10X() function to write the files from matrix market with the following files: barcodes.tsv.gz features.tsv.gz matrix.mtx.gz. Note features.tsv.gz  replaces genes.tsv.

2) Any plans update Write10X() function to take Seurat v3 seurat objects? I tried to run it, but it tells me 
`Write10X(obj = seurat.object.u, dir =  paste(OutdirFinal, "/MTX", sep = "", collapse = ""))
Error: class(obj) not equal to "seurat"`

I'm suing Seurat v3.0.3, which tells me:

`class(seurat.object.u)`
`[1] "Seurat"`
`attr(,"package")`
`[1] "Seurat"` (note capital 'S')

Thanks.

**Comment by daskelly** [comment]
Hi @jdime, thank you for your feedback. I have updated Write10X() to work with Seurat v3 object and to output in a cellranger3-like format. The function outputs cellranger2-like format for Seurat v2 objects, and cellranger3-like format for Seurat v3 objects.

Please note that I have renamed the package to earlycross because a different package for analyzing ATAC data is called Signac. Thus, you will have to re-install using the directions provided in the README. Good luck!

**Comment by jdime** [comment]
Thanks for the quick fix!
All best,
J.

**Comment by AtreeHeart** [comment]
Hello @daskelly , I'm now using Write10X() with Seurat v4, no error occurs, but just want to make sure if this function can also be used with v4 object. 
Thanks

**Comment by daskelly** [comment]
Hello @PeterPYChen I think you should be fine using this function with Seurat v4. It does not appear there were any big changes to objects in v4 per https://satijalab.org/seurat/articles/v4_changes.html. Please let me know if you do encounter errors. Best wishes.

**Comment by AtreeHeart** [comment]
@daskelly Thanks for your quick response, it works smoothly.
